# Generated by Django 2.2.6 on 2020-02-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
