# Generated by Django 2.2.6 on 2020-02-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_register_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, null=True)),
                ('reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Register')),
            ],
        ),
    ]
