# Generated by Django 2.2.6 on 2020-03-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(max_length=100, null=True)),
                ('roll', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
                ('reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Register')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, null=True)),
                ('reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Register')),
            ],
        ),
    ]
