# Generated by Django 2.2.6 on 2020-03-01 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_employee_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_time', models.TimeField(null=True)),
                ('d_time', models.TimeField(null=True)),
                ('date1', models.DateField(null=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_time', models.TimeField(null=True)),
                ('d_time', models.TimeField(null=True)),
                ('date1', models.DateField(null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Employee')),
            ],
        ),
    ]
