# Generated by Django 2.2.6 on 2020-03-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_attendance_staff_attendance_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_staff',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attendance_teacher',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
