# Generated by Django 2.2.6 on 2020-03-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200301_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_staff',
            name='date1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_teacher',
            name='date1',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
