# Generated by Django 2.2.6 on 2020-03-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20200301_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_cat', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField(null=True)),
                ('isbn', models.IntegerField(null=True)),
                ('b_name', models.CharField(max_length=30, null=True)),
                ('author', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Book_Category')),
            ],
        ),
    ]
