# Generated by Django 2.2.6 on 2020-03-02 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_book_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('deposit', models.IntegerField(null=True)),
                ('l_date', models.DateField(null=True)),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
        ),
    ]
