# Generated by Django 2.2.6 on 2020-03-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='e_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='s_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_id',
            field=models.IntegerField(null=True),
        ),
    ]
