# Generated by Django 3.1.6 on 2021-04-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20200303_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='clas',
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift1', models.BooleanField(default=False, null=True)),
                ('shift2', models.BooleanField(default=False, null=True)),
                ('present', models.BooleanField(default=False, null=True)),
                ('attend_date', models.DateField(auto_now=True, null=True)),
                ('clas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='clas',
            field=models.ManyToManyField(blank=True, null=True, to='school.Class'),
        ),
    ]
