# Generated by Django 3.1.6 on 2021-04-25 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0011_auto_20210423_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='attend_date',
            field=models.DateField(null=True),
        ),
    ]
